name: travelman
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.0+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fast_i18n: ^1.6.0
  apple_sign_in: ^0.1.0
  animated_bottom_navigation_bar: ^0.1.2+2
  cached_network_image: ^2.3.3
  carousel_pro: ^1.0.0
  cloud_firestore: ^0.14.1+3
  connectivity: ^0.4.9+5
  cupertino_icons: ^1.0.0
  dots_indicator: ^1.0.0
  easy_localization: ^2.3.3
  # facebook_audience_network: ^0.7.1
  firebase_analytics: ^6.0.2
  firebase_admob: ^0.10.0+2
  firebase_auth: ^0.18.1+2
  firebase_core: ^0.5.0+1
  cloud_functions: ^0.6.0
  firebase_messaging: ^7.0.3
  firebase_storage: ^4.0.1
  firebase_in_app_messaging: ^0.2.0+3
  flutter_facebook_login: ^3.0.0
  flutter_html: ^0.11.1
  flutter_icons: ^1.1.0
  flutter_staggered_animations: ^0.1.2
  flutter_widget_from_html: ^0.5.1+3
  flutter_polyline_points: ^0.2.4
  geo: ^0.2.4
  location: ^3.1.0
  geocoder: ^0.2.1
  google_fonts: ^1.1.1
  google_maps_flutter: ^1.0.3
  google_sign_in: ^4.5.5
  html: ^0.14.0+4
  html_unescape: ^1.0.1+3
  http: ^0.12.2
  image_picker: ^0.6.7+12
  intl: ^0.16.1
  launch_review: ^2.0.0
  line_icons: ^0.2.0
  md2_tab_indicator: ^1.0.2
  package_info: ^0.4.0+16
  provider: ^4.3.2+2
  share: ^0.6.5+3
  shared_preferences: ^0.5.12+2
  skeleton_text: ^1.0.0
  sliding_up_panel: ^0.3.5
  toast: ^0.1.5
  url_launcher: ^5.7.5
  font_awesome_flutter: ^8.10.0
  direct_select: ^1.1.0
  flutter_local_notifications: ^1.4.4+2
  uuid: ^2.0.4
  dotted_line: ^2.0.2

  #mobx related stuff
  flutter_modular: ^2.0.1
  mobx: ^1.0.2+2
  flutter_mobx: ^1.0.1
  freezed_annotation: ^0.11.0

  #other stuff
  json_annotation: ^3.0.1
  meta: ^1.1.8
  logger: ^0.9.1
  timeago: ^2.0.26
  path_provider: ^1.6.7
  permission_handler: ^5.0.0+hotfix.8
  flutter_cache_manager: ^1.3.0
  flutter_ringtone_player: ^2.0.0
  country_pickers: ^1.2.0
  email_validator: ^1.0.4
  profanity_filter: ^1.0.2
  wallpaper_manager: ^1.0.7
  flutter_sim_country_code: ^0.0.3
  image_downloader: ^0.20.0

  #
  shimmer: ^1.0.1
  badges: ^1.1.0
  awesome_dialog: ^1.0.1
  bubble: ^1.1.9+1
  photo_view: ^0.10.1
  bot_toast: ^3.0.0
  flutter_staggered_grid_view: ^0.3.0
  popup_menu: ^1.0.5
  flare_flutter: ^2.0.1
  flutter_widgets: ^0.1.12
  pull_to_refresh: ^1.5.8
  styled_widget: ^0.2.0+1
  flutter_pagewise: ^1.2.3
  uic: ^0.5.0
  flutter_spinkit: ^4.1.2+1
  pin_code_fields: ^5.0.1
  flappy_search_bar: ^1.7.2
  settings_ui: ^0.3.0
  day_night_switcher: ^0.1.0+1
  auto_size_text: ^2.1.0
  rate_my_app: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"






flutter:

  uses-material-design: true






  assets:
    - assets/images/search.png
    - assets/images/travel1.png
    - assets/images/travel2.png
    - assets/flr/success.flr
    - assets/images/travel4.png
    - assets/images/travel5.png
    - assets/images/travel6.png
    - assets/images/empty.png
    - assets/images/restaurant.png
    - assets/images/hotel.png
    - assets/images/splash.png
    - assets/images/icon.png
    - assets/images/hotel_pin.png
    - assets/images/restaurant_pin.png
    - assets/images/destination_map_marker.png
    - assets/images/driving_pin.png
    - assets/images/empty_chat.png
    - assets/images/icon_user.png
    - assets/images/adrar.jpg
    - assets/images/alger.jpg
    - assets/images/bedjaia.jpg
    - assets/images/home1.jpg
    - assets/images/hotel.jpg
    - assets/images/ibis.jpg
    - assets/images/Meridien.jpg
    - assets/images/one.png
    - assets/images/plazamap.png
    - assets/images/sheraton.jpg
    - assets/images/three.png
    - assets/images/tlemcen.jpg
    - assets/images/two.png
    - assets/images/airline_logos/2B.png
    - assets/images/airline_logos/2I.png
    - assets/images/airline_logos/2K.png
    - assets/images/airline_logos/2M.png
    - assets/images/airline_logos/3K.png
    - assets/images/airline_logos/3R.png
    - assets/images/airline_logos/4J.png
    - assets/images/airline_logos/4Q.png
    - assets/images/airline_logos/4U.png
    - assets/images/airline_logos/PC.png
    - assets/images/airline_logos/DP.png
    - assets/images/airline_logos/W9.png
    - assets/images/airline_logos/KC.png
    - assets/images/airline_logos/IO.png
    - assets/images/airline_logos/IQ.png
    - assets/images/loading.gif
    - assets/images/blurred_pic.jpg
    - assets/translations/
    - assets/images/nature/

  fonts:

    - family: Muli
      fonts:
        # - asset: fonts/Montserrat-Light.ttf
        #   weight: 400
        - asset: fonts/Muli-Regular.ttf
          weight: 500
        - asset: fonts/Muli-Medium.ttf
          weight: 600
        - asset: fonts/Muli-SemiBold.ttf
          weight: 700
        - asset: fonts/Muli-Bold.ttf
          weight: 800
